# ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/ADTMap.o

# ADTLinkedList_test_OBJS	= ADTLinkedList_test.o $(MODULES)/ADTLinkedList.o

ADTBKTree_test_OBJS = ADTBKTree_test.o $(MODULES)/ADTMap.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o 

# ADTIndex_test_OBJS = ADTIndex_test.o $(MODULES)/ADTIndex.o $(MODULES)/ADTMap.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o $(MISC)/misc.o

# misc_test_OBJS = misc_test.o $(MODULES)/ADTMap.o $(MODULES)/ADTLinkedList.o $(MISC)/misc.o $(MODULES)/ADTEntryList.o

# core_test_OBJS = core_test.o $(MODULES)/ADTIndex.o $(MODULES)/ADTMap.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o $(MISC)/misc.o $(CORE)/core.o

#test_OBJS = test.o $(MODULES)/ADTIndex.o $(MODULES)/ADTMap.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o $(MISC)/misc.o $(CORE)/core.o

# Ο βασικός κορμός του Makefile
include ../common.mk