# ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/ADTMap.o

# ADTLinkedList_test_OBJS	= ADTLinkedList_test.o $(MODULES)/ADTLinkedList.o

ADTBKTree_test_OBJS = ADTBKTree_test.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o 

# Ο βασικός κορμός του Makefile
include ../common.mk