test_through_OBJS = $(TEST_DRIVER)/test_through.o $(MODULES)/ADTEntryList.o $(MODULES)/ADTIndex.o $(MODULES)/ADTBKTree.o $(MODULES)/ADTMap.o $(MODULES)/ADTLinkedList.o $(MISC)/misc.o $(CORE)/core.o

test_through_ARGS = ../test_data/small_test.txt 180
# Ο βασικός κορμός του Makefile
include ../common.mk