main_OBJS = main.o $(MODULES)/ADTMap.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o $(MODULES)/ADTIndex.o $(MODULES)/ADTBKTree.o $(MISC)/misc.o

main_ARGS = Document1

# Ο βασικός κορμός του Makefile
include ../common.mk