main_test_OBJS = main.o $(MODULES)/ADTMap.o $(MODULES)/ADTLinkedList.o $(MODULES)/ADTEntryList.o $(MODULES)/ADTIndex.o $(MODULES)/ADTBKTree.o $(MISC)/misc.o

# Ο βασικός κορμός του Makefile
include ../common.mk